contentType: Card
UserActions:
  cardId: !!int 9
  hasNotifications: !!bool false
  isIsoloated: !!bool false
  maxItems: !!int 3
  pinnable: !!bool true
title: Used
name: graph-used
CollectionModeField: null
MaxItemsField: null
PriorityField: null
StreamSource: null
CardComponent: graph-used/graph-used-card
StoreMetadataField: null
CommonPart:
  Owner: !!int 2
  Container: null
  CreatedUtc: 2019-02-22T10:47:32.2466828Z
  PublishedUtc: 2019-02-22T10:47:32.2606127Z
  ModifiedUtc: 2019-02-22T10:47:32.2466828Z
  VersionCreatedUtc: 2019-02-22T10:47:32.2466828Z
  VersionPublishedUtc: 2019-02-22T10:47:32.2606127Z
  VersionModifiedUtc: 2019-02-22T10:47:32.2466828Z
ServicePart:
  ConnectorTypeName: ScriptConnector
  ConnectorTypeId: !!int 5
  ConnectorName: ms-graph
  ServiceName: listUsed
  Url: ~/api/adenin.GateKeeper.Connector/ms-graph/listUsed
  ServiceParameters: '{}'
SearchContextPart:
  Query: null
  Interface: null
CommandPart:
  CommandType: None
  Command: 
  DefaultDate: null
  Intent: null
  Ext: {}
AppPart:
  App: null
  Url: 
  ExtUrl: 
  Priority: !!int 0
  AppFaceId: !!int 0
  Category: orange
  Icon: now:search
  CSSClasses: null
  Enabled: !!bool false
  NewWindow: !!bool false
  UrlWithId: !!bool true
  AvailableAppFaceRecords: null
  HasPattern: !!bool false
RoleViewPermissionsPart:
  AllowedRoles: []
  Audiences: []
  Mandatory: False
RecurringTaskPart:
  Schedule: '- - - - -'
  ActivityType: adenin.Now.Activities.CardTask.UpdateCard
  StartDateUtc: null
  EndDateUtc: null
  NextOccurrenceUtc: null
  Priority: !!int 5
  Status: Enabled
  NowFlag: 0
  LastExecutionUTC: null
  EnableWebHook: !!bool false
  WebHookToken: null
